import type { Locale } from "@/i18n/config";

export type IndustryCategory = {
  id: string;
  title: Record<Locale, string>;
  items: Record<Locale, string[]>;
};

export const industryCategories: IndustryCategory[] = [
  {
    id: "machinery",
    title: {
      pl: "Maszyny i urządzenia przemysłowe",
      uk: "Промислові машини та обладнання",
      ru: "Промышленные машины и оборудование",
      de: "Industriemaschinen und Anlagen",
      zh: "工业机械与设备",
    },
    items: {
      pl: [
        "maszyny dla branży opakowaniowej i papierniczej",
        "maszyny spożywcze",
        "linie do przetwórstwa i produkcji",
        "urządzenia medyczne i SPA",
        "maszyny budowlane",
      ],
      uk: [
        "машини для пакувальної та паперової галузі",
        "харчове обладнання",
        "лінії переробки та виробництва",
        "медичне та SPA-обладнання",
        "будівельна техніка",
      ],
      ru: [
        "машины для упаковочной и бумажной отрасли",
        "пищевое оборудование",
        "линии переработки и производства",
        "медицинское и SPA-оборудование",
        "строительная техника",
      ],
      de: [
        "Maschinen für Verpackungs- und Papierindustrie",
        "Lebensmittelmaschinen",
        "Verarbeitungs- und Produktionslinien",
        "Medizin- und SPA-Geräte",
        "Baumaschinen",
      ],
      zh: [
        "包装与造纸机械",
        "食品机械",
        "加工与生产线",
        "医疗与SPA设备",
        "工程机械",
      ],
    },
  },
  {
    id: "battery",
    title: {
      pl: "Technologie akumulatorowe i rozwiązania energetyczne",
      uk: "Акумуляторні технології та енергетичні рішення",
      ru: "Аккумуляторные технологии и энергетические решения",
      de: "Batterietechnologien und Energielösungen",
      zh: "电池技术与能源解决方案",
    },
    items: {
      pl: [
        "ogniwa LFP i NMC",
        "ogniwa pryzmatyczne i cylindryczne",
        "systemy BMS",
        "pakiety akumulatorowe",
        "akumulatory przemysłowe",
        "magazyny energii ESS",
        "stacje ładowania",
      ],
      uk: [
        "елементи LFP та NMC",
        "призматичні та циліндричні елементи",
        "системи BMS",
        "акумуляторні пакети",
        "промислові акумулятори",
        "системи накопичення енергії ESS",
        "зарядні станції",
      ],
      ru: [
        "элементы LFP и NMC",
        "призматические и цилиндрические элементы",
        "системы BMS",
        "аккумуляторные пакеты",
        "промышленные аккумуляторы",
        "системы накопления энергии ESS",
        "зарядные станции",
      ],
      de: [
        "LFP- und NMC-Zellen",
        "prismatische und zylindrische Zellen",
        "BMS-Systeme",
        "Batteriepakete",
        "Industriebatterien",
        "Energiespeichersysteme ESS",
        "Ladestationen",
      ],
      zh: [
        "LFP与NMC电芯",
        "方形与圆柱电芯",
        "BMS系统",
        "电池包",
        "工业电池",
        "ESS储能系统",
        "充电站",
      ],
    },
  },
  {
    id: "emobility",
    title: {
      pl: "Elektromobilność i komponenty",
      uk: "Електромобільність та компоненти",
      ru: "Электромобильность и компоненты",
      de: "Elektromobilität und Komponenten",
      zh: "电动出行与零部件",
    },
    items: {
      pl: [
        "motocykle elektryczne",
        "silniki i sterowniki",
        "rozwiązania akumulatorowe",
        "drony",
        "pojazdy",
        "opony",
        "części samochodowe",
      ],
      uk: [
        "електромотоцикли",
        "електродвигуни та контролери",
        "акумуляторні рішення",
        "дрони",
        "транспортні засоби",
        "шини",
        "автозапчастини",
      ],
      ru: [
        "электромотоциклы",
        "электродвигатели и контроллеры",
        "аккумуляторные решения",
        "дроны",
        "транспортные средства",
        "шины",
        "автозапчасти",
      ],
      de: [
        "Elektromotorräder",
        "Motoren und Steuerungen",
        "Batterielösungen",
        "Drohnen",
        "Fahrzeuge",
        "Reifen",
        "Autoteile",
      ],
      zh: [
        "电动摩托车",
        "电机与控制器",
        "电池解决方案",
        "无人机",
        "车辆",
        "轮胎",
        "汽车零部件",
      ],
    },
  },
  {
    id: "chemistry",
    title: {
      pl: "Chemia i surowce",
      uk: "Хімія та сировина",
      ru: "Химия и сырьё",
      de: "Chemie und Rohstoffe",
      zh: "化工与原材料",
    },
    items: {
      pl: [
        "dodatki paszowe",
        "składniki funkcjonalne",
        "surowce dla przemysłu",
        "LLDPE, LDPE i HDPE",
        "chemia przemysłowa",
        "materiały klejące",
      ],
      uk: [
        "кормові добавки",
        "функціональні інгредієнти",
        "сировина для промисловості",
        "LLDPE, LDPE та HDPE",
        "промислова хімія",
        "клейові матеріали",
      ],
      ru: [
        "кормовые добавки",
        "функциональные ингредиенты",
        "сырьё для промышленности",
        "LLDPE, LDPE и HDPE",
        "промышленная химия",
        "клеевые материалы",
      ],
      de: [
        "Futtermittelzusätze",
        "funktionelle Inhaltsstoffe",
        "Industrierohstoffe",
        "LLDPE, LDPE und HDPE",
        "Industriechemie",
        "Klebstoffe",
      ],
      zh: [
        "饲料添加剂",
        "功能性成分",
        "工业原料",
        "LLDPE、LDPE与HDPE",
        "工业化学品",
        "粘合材料",
      ],
    },
  },
  {
    id: "packaging",
    title: {
      pl: "Papier, opakowania i materiały",
      uk: "Папір, упаковка та матеріали",
      ru: "Бумага, упаковка и материалы",
      de: "Papier, Verpackungen und Materialien",
      zh: "纸张、包装与材料",
    },
    items: {
      pl: [
        "papier kraft",
        "karton GC1, GC2 i FBB",
        "papier do produkcji kubków",
        "folia PET",
        "surowce opakowaniowe",
        "papiery specjalistyczne i termoodporne",
      ],
      uk: [
        "крафт-папір",
        "картон GC1, GC2 та FBB",
        "папір для виробництва стаканчиків",
        "плівка PET",
        "упаковочна сировина",
        "спеціалізовані та термостійкі папери",
      ],
      ru: [
        "крафт-бумага",
        "картон GC1, GC2 и FBB",
        "бумага для производства стаканчиков",
        "плёнка PET",
        "упаковочное сырьё",
        "специализированные и термостойкие бумаги",
      ],
      de: [
        "Kraftpapier",
        "Karton GC1, GC2 und FBB",
        "Papier für Becherproduktion",
        "PET-Folie",
        "Verpackungsrohstoffe",
        "Spezial- und hitzebeständige Papiere",
      ],
      zh: [
        "牛皮纸",
        "GC1、GC2与FBB纸板",
        "纸杯用纸",
        "PET薄膜",
        "包装原材料",
        "特种及耐热纸",
      ],
    },
  },
  {
    id: "textiles",
    title: {
      pl: "Tekstylia i materiały techniczne",
      uk: "Текстиль та технічні матеріали",
      ru: "Текстиль и технические материалы",
      de: "Textilien und technische Materialien",
      zh: "纺织品与工程材料",
    },
    items: {
      pl: [
        "polar",
        "tkaniny bawełniane i syntetyczne",
        "tkaniny mieszane",
        "tkaniny techniczne",
        "materiały specjalistyczne",
        "produkty tekstylne",
      ],
      uk: [
        "фліс",
        "бавовняні та синтетичні тканини",
        "змішані тканини",
        "технічні тканини",
        "спеціалізовані матеріали",
        "текстильні вироби",
      ],
      ru: [
        "флис",
        "хлопковые и синтетические ткани",
        "смешанные ткани",
        "технические ткани",
        "специализированные материалы",
        "текстильные изделия",
      ],
      de: [
        "Fleece",
        "Baumwoll- und Synthetikstoffe",
        "Mischgewebe",
        "Technische Textilien",
        "Spezialmaterialien",
        "Textilprodukte",
      ],
      zh: [
        "摇粒绒",
        "棉质与合成面料",
        "混纺面料",
        "技术织物",
        "特种材料",
        "纺织制品",
      ],
    },
  },
  {
    id: "construction",
    title: {
      pl: "Budownictwo i wyposażenie specjalistyczne",
      uk: "Будівництво та спеціалізоване обладнання",
      ru: "Строительство и специализированное оборудование",
      de: "Bauwesen und Spezialausrüstung",
      zh: "建筑与专业设备",
    },
    items: {
      pl: [
        "domy kontenerowe i modułowe",
        "wyposażenie kolejowe",
        "materiały budowlane",
        "maszyny i wyposażenie specjalistyczne",
      ],
      uk: [
        "контейнерні та модульні будинки",
        "залізничне обладнання",
        "будівельні матеріали",
        "спеціалізовані машини та обладнання",
      ],
      ru: [
        "контейнерные и модульные дома",
        "железнодорожное оборудование",
        "строительные материалы",
        "специализированные машины и оборудование",
      ],
      de: [
        "Container- und Modulhäuser",
        "Schienenausrüstung",
        "Baumaterialien",
        "Spezialmaschinen und -ausrüstung",
      ],
      zh: [
        "集装箱与模块化房屋",
        "铁路设备",
        "建筑材料",
        "专业机械与设备",
      ],
    },
  },
  {
    id: "consumer",
    title: {
      pl: "Produkty konsumenckie i Private Label",
      uk: "Споживчі товари та Private Label",
      ru: "Потребительские товары и Private Label",
      de: "Konsumgüter und Private Label",
      zh: "消费品与自有品牌",
    },
    items: {
      pl: [
        "naczynia",
        "odzież",
        "zabawki",
        "wyroby żeliwne",
        "folie",
        "artykuły dla zwierząt",
        "inne produkty wykonywane pod marką klienta",
      ],
      uk: [
        "посуд",
        "одяг",
        "іграшки",
        "чавунні вироби",
        "плівки",
        "товари для тварин",
        "інші продукти під маркою клієнта",
      ],
      ru: [
        "посуда",
        "одежда",
        "игрушки",
        "чугунные изделия",
        "плёнки",
        "товары для животных",
        "другие продукты под маркой клиента",
      ],
      de: [
        "Geschirr",
        "Bekleidung",
        "Spielzeug",
        "Gusseiserzeugnisse",
        "Folien",
        "Tierbedarf",
        "weitere Produkte unter Kundenmarke",
      ],
      zh: [
        "餐具",
        "服装",
        "玩具",
        "铸铁制品",
        "薄膜",
        "宠物用品",
        "其他客户品牌产品",
      ],
    },
  },
];

export function getIndustryCategories(locale: Locale) {
  return industryCategories.map((cat) => ({
    id: cat.id,
    title: cat.title[locale],
    items: cat.items[locale],
  }));
}
